# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:H4tezPJyprUMOGtCVZxbiDs=,iv:M3wiQdurcjG8rBCY7n5KZAO0MS1aG5+5cUGPL+tEeH8=,tag:XY7Tu8KDr7P/wyVxTy3e7w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pufbF8uo4t2WOrf44rSMUj0kMQ==,iv:llVo+oF1GRzBz5J12zYDzXwr4hiwaaEu0/bGzKNsGho=,tag:/CfZtkIg6mmggMSGtf6mJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-19T22:34:10Z"
    mac: ENC[AES256_GCM,data:uGNmoM/379lsosWjX+y7p1hfqVbsDrVtOdli7I3B2sLbHIusPtRya0aDFvaPFt1NSwkSDMnxcL9G+TNtVpcahom/hNjGAtooDqylfvHDrl2szHmCuMbhdQp43XP9ohLAnVvK3vQKYGf+dYGeYkJJqMWOb+jVW0GAOXKozrJU1V8=,iv:K6zF/NsXQa7hEmUCvyCS1VPMe3iWnit6cZmiXXNqgQk=,tag:sVmqinJrSR20Jm8EmpY1Ng==,type:str]
    pgp:
        - created_at: "2021-11-19T22:34:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyQ7feC2Of/FAQ/9EG6W9fQms190ElDqquH7W+eDXTFgo86ZE9RfVYsLUdEG
            fJ6t8hNo3F6GHCzvGB6H7SED0ADEfF6TMisXVpEjD7iw4A5/maZNbXTeR/SHb9kW
            1Go+lLYHvKUyqQCUoqmDBK0Isuc8ae0m2fuJJxmbHnBJ2FOtLNdWUrozoEFM00uE
            dzjXQMM5gqlZOXPeRzrXPQ1TpR7V0510Dsbnk0igF+jimFpe9BPPXbV4hjG7pzZO
            fS1zJicThAGegEbzafnOt997SW2MGZiKKWybd2jcL26xV1aEyi5Q0LUONF+EFD94
            at9a50pY23xiNwxSEJ9pMyv4ZGsN3dgtkvN2qqSRtXMYoM8Lr0atqdSncc6TpdAu
            Iy1pWTRCjjg3rRDcZ5UxiExcbTTAfJ9kiRlpeM88dOMt3rOqo43/Mett0U86SZzd
            wU1sAMkfylt2dL2QYSiGZgiwRS3DDmYLCFJy3qJ+ErHIjOBLVT06ezMyhBWq+Duc
            mMKe6LEwhDUndAU3+mL+r/Y7pQYwBTiKZL/3p/4aRonqUZI8bBp0mzbLxPyzwXhr
            LVii7C6xa4ZRPQAEbRSAn/bkY6MwwkH5Ls641yV57c1tsTBus58y+OsDIAIjeS3Q
            MYmleftjNSnc3hDpUl7T6tlXtpR9rAGtLc5rJkwk/vYN2lxge3KvDY7umIdWZNnU
            aAEJAhA4onW7gH7pnbY0oYUlfJPQVXZ1un7aQX6okYEUtJl7pSsOC0u6tAmNU5aB
            e70lFEbmPnYBL3DJFGAetXDkge3nz2loZoQZkNeeqTgh5fRj4C/ANP5JJ6WemOWa
            BtJfchwNc9g5
            =/Eh8
            -----END PGP MESSAGE-----
          fp: 06D745387E828A2D040F621082A898ED85B4F64B
        - created_at: "2021-11-19T22:34:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42nrMmwcdfpARAAnXFAdFDHkrdL9+DtTqOae7c8wrYGeMw1492ABpap29Jy
            3taTYbd9q0yb6xrWZNCVXOdPetHmI0idZjJ2z0YUEmLp0ZkWwjBTdhFRT2fW1KsA
            4QWDaLrxYSr3q85xTJhlq9bLGQnHZvSk0YC9cqmTyTH3NiVqHpsVg0r8opg+aIo1
            Y0uMVidSDZ9LcFCWs+ha2r7pzjYHfcrdAlRTbJw5D26sifLyKElnsjKKU9zJCrMF
            Gx5yjF+xNG3mWgwiYKD9EnwKb9lIhVH2OT7BOm1BDbO+Vhcn445hAmx3UbZMCecy
            JNUQn59NDeVMUVDV640NCMu2aRRipbp5mwshwafYZXfIgLAi9chnArUGVy/bPtBh
            2FZzM5DIv8e0ariV3SRArVj2t+lBCpgwEco7ZXCalheg/FpSESrPs8IJBm1uUcNL
            X49aUzY0OVqj5bhPYJCMuUu2/um2qq8K88Ly17qAzl/WyIy8DNUFHzDC/ZtvZcz0
            bX7i4O7Z2BKSFIOK2QaNsK4O3RVwFbhSHCUsCjzqvTlCfwEqnbZLMHJFgBgMLxr8
            XyvkeFYgvgyueaqqkVJHdhVYhhpd5tbhc+vprX4dlxhePkvj+di83tXkOcK8zIBi
            ePEBzsr0AGww0jC9GK2HyFnxQr/7afxHZxPsDN7HM0GoAveipCn2zI6orx1QaYPU
            aAEJAhBGhboPwbIFdoXiqYOnRjwDImOc7QbBj3o0Izzmgm2gJYV18+9YJsmhBLWE
            k5qjPTfh0klBm+KAJugs2e5zAlEUbpuAKMFMlYilxbu2aQDy04GBMhjiPXa4lHCo
            ZEkLxpqHVjC2
            =VXWo
            -----END PGP MESSAGE-----
          fp: 8586714C9564B92FD2D6D41B6B14541D374F98EA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
