---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-benji-pv
spec:
  storageClassName: backup-benji
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.167.5
    path: /mnt/SG6TB2/benji
  mountOptions:
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backup-benji-pvc
  namespace: backup-system
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: backup-benji
  resources:
    requests:
      storage: 1Mi