# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Mt6QomonZCkXx5quISovGHf19O33fiMwSys7WMe/ychptT4gjgiWkQ==,iv:elTkLfJttiqUfC4i/YEBWXiFyaaXuHdAEsPkTvmbBYI=,tag:OJ5diHSKekx5lBSC2VjwnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-19T22:24:06Z"
    mac: ENC[AES256_GCM,data:yqNtFTdRbtKwYBEjNioNhqQbBTQIjsNHckwfh9rNMvZjd8DDa0EBwMGnpBb+BuKADp4LoOTL5O7D650AyTbqVF3A6N8adqYARerc1RNVxm3Ii7CgbSZGj/b7vRn62v+VPff2AKd0axJCeKN0af0APwVmXo0hLj6QL85g7T0C1Tk=,iv:JZRiJ6rlcxWMcC3FajLOd5AY2Ki5Ad66/SQ+CK3i5Zc=,tag:N4hLWgmKeHEo8u/pFyHIzQ==,type:str]
    pgp:
        - created_at: "2021-11-19T22:24:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyQ7feC2Of/FARAArYEYoH4ndnlTGWx1Jh1HOxBOiH3BKZLMhBkk0IrkLvgV
            rrssO27eBGKfFixUV2NpQLew3f6YSaS2gSHxIWxMr2HkwdVT26KCMwsx6iogX5/E
            /GkEiag8kUf5W2ReDPhBO6yyYlkdCbJ11Ye+hw9w5a52O0j1uBGtfHkzUF+YBZNC
            4qeN+cmdyQUubKXlm3L2c5foDv/mDCw+t3595HG7j3u6pjxgf0shulYMAf4T448l
            Kmq5cKwnEk/MFPT5lVme4273k7M3K3gXYNnwnM2k4wLwfl9zqrgRChuJBVY2SMMv
            2H+FqK3b0IHW7GCUrwBeVSO69XfbEgpYn3RgapdCnEoNJ7BMjTkNGCnOL+uGqt+9
            QmL3CmCx57C1ZNQK7zbi6TkwaHnWYV9o7aH/KCa3wJ0takBtfZcQ9he+RX9KQJRX
            VAr7Mu6bBTdwmMBhR7mMjKWQQPatoobXkz2kWEVMDqWg/S2zNOMM6fceoc1SfZO/
            9H0bk75U+oORR9CC6q8MhLRvgNe+0NnsfbOm1OncULxEGy2WPA/0smaKaXIhxxH2
            yeARLuhjkoTFA76OlQtTEqZgeEN+wRmKtseQySVZ/wxXwA5CRvuCEE83iEOr7Ijh
            3V3++VbgZvQWmtcoppL/AZSEdi3JZKRBFwMma/X7VhJq0q7EIsrLIm7v7j/fORrU
            aAEJAhBw1LBH2/hS5WwCVPHLZE+aygftQzGyOyulX1DC2J/3MbulrQdq0O+4diX1
            fL8AKmyK8q54H4hk2NdLpbFtAoJl4KhMDDkZU6SeclbusBh12hposYrkuDJF/b0v
            RFT97Djjm/eI
            =l74q
            -----END PGP MESSAGE-----
          fp: 06D745387E828A2D040F621082A898ED85B4F64B
        - created_at: "2021-11-19T22:24:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42nrMmwcdfpARAAjDtqiTg2Mg/BQD34QgC02FLFwg0kbZAQvPt34KI1W/YT
            iItdO5U5+j7wBmMkKpBpZ+f4lmfJ3VIh+xXzLLKVjrRjJOtYxVrDh3nMxpujFlKt
            6WHRF+WY4ZQad3HhGLdpe+kSa/rb5ZLUVq4ZKOy0980B5dTYk78n27goAeqKXE/V
            YqivvdZWTtYDKs9JjOxI+wfXHL3IIAsP2LW2ZriNbDLzCrj0W4bguF/lolI3KA8o
            l91CdD4C/hCwxrqCe2SiusYKhg/rZ0f6g+Tz/E3k1RwUzFARufP7ljyrbc6ArnQ/
            SKIjbtdXuJ1oiUoyWNpSpSJT+yP0UZ25NfpEYB1h/+tlNuJ9pVWyj4gVxcygtxWO
            kRlOzUigEPDX8VOGG/3E05mLBUj8JkE+gVVi0JD4+QqL+InRJAcK4mSQa5YNIYwa
            Rin3QmGWkv0gbzdbNGb9Y0UA4d15csAzyakIW7rAKPggt7wP1ZtWQ2dqSe8zvGHq
            PnYe0/BNxU2nlVAJ4OKmp1PdgbIU2gxcJ1Gs5iwUp38P64UcI/xYpX6uuBO22AbI
            nEEG1oM8XwIwuEAJx3MMdWWy+2u0hkh+CNKiateJ2S2RamPv1pMh9GHxuoe2INWm
            qs+8gNVTexmc2pNo564TQ2ONbKZMaEvtdWmpJGGN2fbtObzauwNKGqkNppYkg6PU
            aAEJAhDwkDdo64QTfplB4lYImgvcwo5NT96cLhjRrQov72CfkXrT+bnyIRcE2bYe
            f4kR5h+5vpnqks19C0dHvZShOmEe1jXK3waP250/LWguwSxKJ6/UrGM1I6WOEErm
            FJkr29ACughs
            =Tytl
            -----END PGP MESSAGE-----
          fp: 8586714C9564B92FD2D6D41B6B14541D374F98EA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
