# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:UMIgYg3SOYg5riw/MQcd2+XA0boWlOuVqqcz6CYQ9i5l+B88zA==,iv:VcrVU/ZkM5AP2y09jJrX2TcP5eHTFKtRusriSZZDJXE=,tag:CE7AaH9ETOZvB6+4VNuE2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-19T23:14:12Z"
    mac: ENC[AES256_GCM,data:aLywUtvKVpq7mh8hkTrZiYK+dyYhHXKR+hxwLL5oinuUnFwSdEKgxgTW0Sa9tp6969fGt0SsYj81RQ2YRHo+AmaPSNe5g29NfTpdXKKLBeLU11teueooVjm65+ble5zDLhBUuEsxLe2nAPil09nBbgkdzvrmTEgjb0rfMLuZBEU=,iv:z2/N/NaXfxIx6+dHYpPRrcFfCxB1l0ah6bDWqoyG0+c=,tag:MAT/d+gnc9zsnQhOX+eleA==,type:str]
    pgp:
        - created_at: "2021-11-19T22:34:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyQ7feC2Of/FAQ//UAUWB31Q6q7qPWqq+Wn3ql9MTBvHTEQpz3hFZfHdT4KT
            rWOdXANwnzS8L9SOn1L42mH+FWZtqvaAa0Nf8f5RAiA9QifBBirAKKArPZTwSKSX
            Jg1RMDClUt+PeR7uzm+ENHgxBVBxJK0b16tertOReafLOg7adQn6mcZjRBzr3IMf
            vZzVMKDhtm8V9k1itUYhFmHZNCp7fdFw9tiK5gbuxnSH5WrhTvpDgLJXjAu3i1c6
            f754VN8BIMV84KP45q+u0HQoCOg4C9AQ5zywor8TiVLfTCIExaJUjyOwb5BwXtcE
            NhIvkd4YS2wI+aqk3xUdZ2J583MVlOA3Wb+F3hK7F7+EdkDQjz/z+lSSzLle3F8G
            r921XDn1qh2QmpFBtCF40oW6/28mfxu16Jw3qgKC5lvf4Csf/eENa0i9zSOSzPoy
            VVj+q3ST+dCqAxqWBRota/B9iFZXMgsixquXZ7kAZ6xDJIxXQecAzpSjjp6O+okV
            q+c4Qk+DFm8mbQd/07VMin9yTLHmTu/UNpUMlRozdW9ErPy1uYoOUqQIkXQBbIbH
            GQ2qz1+4UQs5T1NAwYcg8TfuVfItLWnqn8mxvcLg60qk9wctBjk2gwnRRL3dUnNU
            cE9TlYrf0p27N5TjNIsXOcc/T5a1cIvveyrff7urD50Wi6OTz5ADbXVJ1LszKsDU
            aAEJAhCLRaombZF0B4O2W+iR8/mbyzpmlaOQnuj1jKCIaGj/Rm78u70D0N/cZIFC
            GMTGsF0a7iLGaG2TGhDkL5m48j3eX7Bj/AVBETpNyb7HBOLQ18B/uI1tIhFq5fM+
            CeAgcD+dDcSC
            =LUEl
            -----END PGP MESSAGE-----
          fp: 06D745387E828A2D040F621082A898ED85B4F64B
        - created_at: "2021-11-19T22:34:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42nrMmwcdfpAQ/8D+kvX1kGjScsKxcoWM97G0B+T3wvdDzwrMK0Qrc5Hs32
            9k92gZpgkdaVMyftXz3jjI4YdCpgIU5NKEg3ZIKDDvUrPsBZqTEe6zLSeZ8TFnxN
            4sojD+6OFp4BHax6AKXWwfsZSqTAa81FKOI/wcDQM5VfwQLEaYZ9Ca8QyNIQtYSQ
            NkqFlDHtK0KZ+K8tnRAIDgw+vejTD7RqBOuxilrpl/WfCEK1t+u7g++8VMlwPXSN
            p1k9Fdh0ECESxH9Lmu5i0W9J4hLjK04AguiTbJnHmq9Eq/nbkQYvJtd76W8Xc6SH
            EoppyUAq3uJXSkI/+feTydp1a6lG2TlfpjbYZjJSVIqb+q4a81ZYeBn64178VQuW
            FAOPliuR1PweUgcvMRbReNn46e44UMQGiXIzd6CbSoOLsyu+bkcW8DgNclEOTJGK
            Tn467HnCrNlrD6McP/B64HNTDU2m3VxufkvCVn10jtzbqQtP+pgeseC259v5sgoL
            iH5Bp+25uqLZyxRtLWGXYL8J2q9Y5fsoLs+2Lnt0VvtKr5ZO/T0nHDloGIwfLF3p
            dHi1ELF1aiidJyI6pbOLig6w94gcEhmcKG+6uxuy4gelq2mo2UoRc2WCTho+wcTz
            RaYb2PXxhmNMch+b5h1VJrC0mJSEBp493TsV13DwpwF3TTDHnaOpD6tHS0y+AaPU
            aAEJAhB1i0MG/oZCYz0AfpHzkmbzK6D/1WI+ZPYDYghHRdf9XGmJhXnZAB6va1f2
            G2X9aL8TM3vUprqmJwZOufwi49N4my6UfpUzBXRms+WPRtlf1+UQRnIbiZi36t7g
            Rl5aI8gbf87e
            =Ra7W
            -----END PGP MESSAGE-----
          fp: 8586714C9564B92FD2D6D41B6B14541D374F98EA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
