apiVersion: v1
kind: Secret
metadata:
    name: velero-minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:PS19c9lCSIAevcnpQy+BJBsb1cMCTdS3F3vMP7UGD1WIRTOmN0wC8H+MKPVaHp1tQDwsYuav2XZksUFZ1HB6F+EJRqLda7fsQB20Owf5qA==,iv:XKjIjXUL37NhA3P9Sfrri73oqYW9jAYjeSDrsXHacU0=,tag:S3jg41nvPbn+Bueo4LitmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-29T09:45:13Z"
    mac: ENC[AES256_GCM,data:I7GQ1CiS7+xq0kZVtoI2IJM4nYiBjcYiB7+J/1lRFrjmcWFusQNEj2Dqp6wBiG2VBOe0+v2XSsJAiGM/jy5hWlJs9K3IJeGsr4CffgNtanoTT1YTrjXrTu4yd5wMuYiAOJFRsk1rHCnERZ6l4hzCpfRQRlekEXYauq5PGO9FQEE=,iv:EVKfY+EojUo5GOqJtPaAQdC9ROpy2IdV3SAIV9Pnld4=,tag:OpzAc6zoSMWOAKJHtgf4VA==,type:str]
    pgp:
        - created_at: "2021-11-29T09:45:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyQ7feC2Of/FARAAi8bhOnOFZ6UQL8Na16aUdKxqveZrLKaEPxaE1+rostY1
            LRwHHg10zbXKlScFyjEwSVO5P4fHwzfneoNimSKZkZ2VQz3+GP2BPUVP2Syw5K5m
            33xQ6FBsHhIhF86SAV/JOOOdy7aNdJBMmjSneJ7l7VGZ5bWKM55zXiK3gMpPDuWC
            LIW2h44cZMRV5hSdomrYB/zok0BK/zmqBm1bOknBwm946q8P6JZIq3+TbNLSf3hN
            b+jtyhRcoJcsx+fMulIlC1wl9/IRoS7CM6ufzWWyfZhgQaqEH8o2UqDT+2YetAsS
            uxDw4dBf7Yja79YbMsDQeCYVpJMSdVPq3DDGlMeo4Os5vVELWdz/KZm+hGpIqBdu
            hBvnhYNPLIaez4ERgas364oanr6KlIKpRMgFq9O0h6tizmzaLVXbot9noRcytS4V
            Xt83Cw0FG0nx9aodeFEC9bt5PH055NZcn/XG4aInwPqiOm6cE7WaS3n/bf4MbOg2
            Jp0zVCy49rh/FOway9fOk+KKQ3jFvu2uhBClQpf/74uIx6Q3BMRZR/ryvb/eruOv
            S4tQpdg642Q8EKz55v4YB0V24M3A15pvosCppoPRY6l5nt/8FyBgk1Zi8Q3ew5zK
            cpd5Bgq1bGOKvMHnx61EqaCkjcdMOB5KKwr8DZDxeJAegVFzpgnsssEadHZ5i8DU
            aAEJAhDJsP8vJhP2rEL6LGACVZLeHfxOW79HNrLNm1wHmVgtGjYqgg+G6R43WUpE
            xnTJ2vq89S5G62xIRAaZFMx0ye//fii3YDwK1PKa4r7AaXZdg1hYx+ZyQ+vAHGCC
            A27yw3Gh7INp
            =/DM5
            -----END PGP MESSAGE-----
          fp: 06D745387E828A2D040F621082A898ED85B4F64B
        - created_at: "2021-11-29T09:45:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42nrMmwcdfpAQ/+PN4RbEhd93jeQnELZVx4Fm552xElXXjYu34LuZQHtxQA
            OxxMw38OXDfhaLZkS/WFEZr9AGB9ZvQ+/iNSxtCgfLze2G/JJV5qAo+T5XVkB4CG
            ECRqJRQjdHvZ52zCskG45Sv9kiumJmc/GzWdCoPYJtVshL5shyLtpXIAeHjChxxk
            gEziZG6x1ljrygd780Z34kIF5E6Sd199ucpeNj099OwwSVIPm9pjsnBp5sNqxQGT
            Pq+4cBClm63sLourvohsjFRx4HCNBLNn9stHLpxcC6XArkjf7E1I61ID9iSC83LG
            lhxdyaDZmR6sIQUH6MwJpoMo80vJa2IeINukOOCMv+WjdL/U/p8vAXCxRardRGyz
            Flx9gMNly0e/Db1VLvOycXsQvL3+1N5OmZOtC2OXwwXb9yXtvfiYluTEW6yV9Vv8
            LX7ERX+5igmzxWceraohmch9G60+A8TKNMTfsNcrNiCyP1kvPgQvTMbifLpjNkTn
            qv5H40YfHzCUyDcM6glnwmI7n6/eNtvSckiUO1mEEdxIWqQb7w6T6dnKEE5xl7bP
            swlbVPuV6fI0PAGUdNoLRWPiktutG8XU+McSUge2gQWVe3kaZqUAYmSccnvyfSWb
            /6SGTuaQ7IcSFThnvR3iDGmc5VhM6jw3fyTgsoUQmhHkR0GApvB1gJq70+W4A3vU
            aAEJAhBZbaSFtaBVSQAJj9R6s7oeZhrnJxTyqYHnDIDz7FxQPTwmjvbjg0tHHMl7
            BaoSod11qj+3RiCuayTSbvwXHVoKAecLX7To0O4hvbgGWx3a55IwSf9o+2tvzJEM
            e/l/QT5Awu6R
            =snIo
            -----END PGP MESSAGE-----
          fp: 8586714C9564B92FD2D6D41B6B14541D374F98EA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
